### ISSUE TITLE
Not working for bots and members 

### ISSUE THREAD

**Issue by Novamiiro** [henryemily098/ServerStats-Bot-Discord.js#1]
i don't understand why but the total is working but for the bot and the members it's not working (only 1 members but we are 5) (only 1 bot be we have 2)

**Comment by henryemily098** [comment]
can i see your code, please? Maybe then it will be a little easier for me to understand the problem

**Comment by Novamiiro** [comment]
(only the total work)

let stats = {
    Guild_ID: "719538816322633728", // Guild ID
    Total_Members: "837638257298767892", // For Total Members Channel ID
    Members: "837031129764593684", // For Members Channel ID
    Bots: "837031159073341450", // For Bots Channel ID
};

 client.on("ready", () => {
    ServerStats()
    setInterval(ServerStats, 10 * 1000 )
}

async function ServerStats() {
    var Guild = client.guilds.cache.get(stats.Guild_ID);
    await Guild.channels.cache.get(stats.Total_Members).setName('Total ' + Guild.memberCount);
    await Guild.channels.cache.get(stats.Members).setName('🤴・citoyens ' +  Guild.members.cache.filter(m => !m.user.bot).size +' casser pour l\'instant');
    await Guild.channels.cache.get(stats.Bots).setName('🤖・bots ' + Guild.members.cache.filter(m => m.user.bot).size+ ' casser pour l\'instant');
}

(i make it for a french rp server)

**Comment by henryemily098** [comment]
Okay so, i have alternate for the code, hopefully, this is works:

let stats = {
  GuildID: "",
  TotalMembers: "",
  Users: "",
  Robots: "",
};

async function HandleCount() {
  console.log(`[Getting Server] | Getting Server by ID . . .`);
  const Guild = client.guilds.cache.get(stats.GuildID);
  console.log(`[Counting] | Counting total members . . .`);
  var TotalMembers = Guild.memberCount;
  console.log(`[Counting] | Counting how much Users . . .`);
  var Users = Guild.members.cache.filter(m => !m.user.bot).size;
  console.log(`[Counting] | Counting how much bots . . .`);
  var RoBots = Guild.members.cache.filter(m => m.user.bot).size;
  console.log(`[Getting TM.Channels] | Getting Channels for Totals Members Numbers . . .`);
  await Guild.channels.cache.get(stats.TotalMembers).setName('Total Members: ' + TotalMembers);
  console.log(`[Getting U.Channels] | Getting Channels for Users Numbers . . .`);
  await Guild.channels.cache.get(stats.Users).setName('Users: ' + Users);
  console.log(`[Getting B.Channels] | Getting channels for RoBots Numbers . . .`);
  await Guild.channels.cache.get(stats.Robots).setName('RoBots: ' + RoBots);
  console.log(`[Success] | Successfully reading Members and Channels!`);
}

My other bot always working with this code.
